#!/bin/sh

set -ue

#TODO
CONF_FILE="/var/lib/mender/mender.conf"

MENDER_ROOTFS_PART_A="$(jq -r .RootfsPartA < "$CONF_FILE")"
MENDER_ROOTFS_PART_B="$(jq -r .RootfsPartB < "$CONF_FILE")"
MENDER_KERNEL_PART_A="$(jq -r .KernelPartA < "$CONF_FILE")"
MENDER_KERNEL_PART_B="$(jq -r .KernelPartB < "$CONF_FILE")"

MENDER_ROOTFS_PART_A_NUMBER="$(echo "$MENDER_ROOTFS_PART_A" | grep -Eo '[0-9]+$')"
MENDER_ROOTFS_PART_B_NUMBER="$(echo "$MENDER_ROOTFS_PART_B" | grep -Eo '[0-9]+$')"

if command -v grub-mender-grubenv-print > /dev/null; then
    PRINTENV=grub-mender-grubenv-print
    SETENV=grub-mender-grubenv-set
else
    PRINTENV=fw_printenv
    SETENV=fw_setenv
fi

active_num="$(${PRINTENV} mender_boot_part)"
active_num="${active_num#mender_boot_part=}"
if test $active_num -eq $MENDER_ROOTFS_PART_A_NUMBER; then
    active=$MENDER_ROOTFS_PART_A
    passive_rootfs=$MENDER_ROOTFS_PART_B
    passive_kernelfs=$MENDER_KERNEL_PART_B
    passive_num=$MENDER_ROOTFS_PART_B_NUMBER
else
    active=$MENDER_ROOTFS_PART_B
    passive_rootfs=$MENDER_ROOTFS_PART_A
    passive_kernelfs=$MENDER_KERNEL_PART_A
    passive_num=$MENDER_ROOTFS_PART_A_NUMBER
fi
passive_num_hex=$(printf '%x' $passive_num)

ensure_correct_root_mounted() {
    if [ "$(stat -L -c %02t%02T $active)" != "$(stat -L -c %04D /)" ]; then
        echo "Mounted root does not match boot loader environment!" 1>&2
        exit 1
    fi
}

case "$1" in
    Download)
        ensure_correct_root_mounted

        # The rootfs.
        file="$(cat stream-next)"
        cat "$file" > "$passive_rootfs"

        # Separate kernel, if applicable.
        file="$(cat stream-next)"
        if [ -n "$MENDER_KERNEL_PART_A" ] && [ -n "$MENDER_KERNEL_PART_B" ]; then
            if [ "$file" = "" ]; then
                echo "Kernel payload missing from artifact" 1>&2
                exit 1
            fi

            cat "$file" > "$passive_kernelfs"

            # Get next entry
            file="$(cat stream-next)"
        fi

        if [ "$file" != "" ]; then
            echo "More than one file in payload" 1>&2
            exit 1
        fi

        # Do a filesystem sync.
        sync
        ;;

    ArtifactInstall)
        ensure_correct_root_mounted
        ${SETENV} -s - <<EOF
mender_boot_part=$passive_num
mender_boot_part_hex=$passive_num_hex
upgrade_available=1
bootcount=0
EOF
        ;;

    NeedsArtifactReboot)
        echo "Automatic"
        ;;

    SupportsRollback)
        echo "Yes"
        ;;

    ArtifactVerifyReboot)
        ensure_correct_root_mounted
        if test "$(${PRINTENV} upgrade_available)" != "upgrade_available=1"; then
            exit 1
        fi
        ;;

    ArtifactVerifyRollbackReboot)
        ensure_correct_root_mounted
        if test "$(${PRINTENV} upgrade_available)" = "upgrade_available=1"; then
            exit 1
        fi
        ;;

    ArtifactCommit)
        ensure_correct_root_mounted
        if test "$(${PRINTENV} upgrade_available)" = "upgrade_available=1"; then
            ${SETENV} upgrade_available 0
        else
            # If we get here, an upgrade in standalone mode failed to boot and the user is trying to commit from the old OS.
            # This communicates to the user that the upgrade failed.
            echo "Upgrade failed and was reverted: refusing to commit!" 1>&2
            exit 1
        fi
        ;;

    ArtifactRollback)
        ensure_correct_root_mounted
        if test "$(${PRINTENV} upgrade_available)" = "upgrade_available=1"; then
            ${SETENV} -s - <<EOF
mender_boot_part=$passive_num
mender_boot_part_hex=$passive_num_hex
upgrade_available=0
EOF
        fi
        ;;
esac
exit 0
